my_project/blog/urls.py
from django.urls import  path

from . import views

app_name = 'blog'

urlpatterns = [
    
     path('',views.post_list,name="post_list"),
     path('<int:id>/',views.post_item,name='post_item')
    
    
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    
]

my_project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        PUBLISHED = 'PB','Published'
        DRAFT = 'DF' , 'Draft'
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default= timezone.now)
    created = models.DateTimeField( auto_now=True)
    updated = models.DateTimeField( auto_now_add=True)
    status = models.CharField(max_length=2 , choices= Status.choices , default=Status.DRAFT)
    
    def __str__(self):
        return self.title
    class Meta :
        ordering = ['-publish' ]
        indexes = [
            models.Index(fields=['-publish'])
        ]

my_project/blog/views.py
from django.shortcuts import render,get_object_or_404

from .models import Post

# Create your views here.
def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post/list.html',{'posts':posts})

def post_item(request, id):
    post = get_object_or_404(Post,id = id , status = Post.Status.PUBLISHED)
    return render(request,'blog/post/item.html',{'post':post})

my_project/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{%block title %}{%endblock%}</title>
        <link rel="stylesheet" href="{% static "css/blog.css"%}">

    </head>
    <body>
        <div class='container'>
            <div id="content">

                {%block content%}
                {%endblock%}


            </div>

            <div id="sidebar">
                <h2>My blog</h2>
                <p>This is my blog</p>

            </div>
        <div/>    
            
    </body>
</html>

my_project/blog/templates/blog/post/item.html
{%extends "blog/base.html" %}
{%block title%}{{post.title}}{%endblock%}
{%block content%}
<h1>{{post.title}}</h1>
<p class="date">
    published {{post.publish}} by {{post.author}}
</p>
{{post.body|linebreaks}}


{%endblock%}

my_project/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title%} My blog {%endblock%}
{% block content %}
    <h1>My blog</h1>
    {% for post in posts%}
        <h2>
            <a href="{% url 'blog:post_item' post.id %}">
                {{post.title}}
            </a>
        </h2>
        <p class = "date">
            Published {{post.publish}} by {{post.author}}

        </p>
        {{post.body|truncatewords:30|linebreaks}}
        <hr>
    {%endfor%}
{%endblock%}        









{endblock}